# Generated by Django 5.2.11 on 2026-03-24 13:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userprofile_role'),
        ('billing', '0001_billing_core'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Передаётся в CloudPayments как InvoiceId', unique=True, verbose_name='ID заказа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма (₽)')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('failed', 'Ошибка / отменён')], db_index=True, default='pending', max_length=10, verbose_name='Статус')),
                ('cp_transaction_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID транзакции CloudPayments')),
                ('cp_data', models.JSONField(blank=True, default=dict, verbose_name='Данные CloudPayments')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Дата оплаты или отказа', null=True, verbose_name='Завершён')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='accounts.account', verbose_name='Аккаунт')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_order', to='billing.billingtransaction', verbose_name='Транзакция биллинга')),
            ],
            options={
                'verbose_name': 'Платёжный заказ',
                'verbose_name_plural': 'Платёжные заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
