# Generated by Django 5.2.11 on 2026-04-07 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_usersession_last_activity'),
        ('billing', '0002_cloudpayments_payment_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(help_text='Код из AVAILABLE_MODULES в billing/constants.py', max_length=40, verbose_name='Код модуля')),
                ('enabled_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подключения')),
                ('expires_at', models.DateTimeField(blank=True, help_text='NULL = бессрочно', null=True, verbose_name='Действует до')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='accounts.account', verbose_name='Аккаунт')),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто подключил')),
            ],
            options={
                'verbose_name': 'Модуль аккаунта',
                'verbose_name_plural': 'Модули аккаунтов',
                'unique_together': {('account', 'module')},
            },
        ),
    ]
