"""
Django settings for transdoki project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "False") == "True"

_allowed = os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1")
ALLOWED_HOSTS = [h.strip() for h in _allowed.split(",") if h.strip()]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Мои приложения
    "accounts",
    "billing.apps.BillingConfig",
    "organizations",
    "persons",
    "vehicles",
    "trips",
    "waybills",
    "integrations",
    "contracts",
    "invoicing",
    "bank",
]

MIDDLEWARE = [
    # Стандартные middleware Django
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Кастомные middleware проекта
    "accounts.middleware.ImpersonationMiddleware",
    "accounts.middleware.SessionActivityMiddleware",
    "accounts.middleware.CurrentOrganizationMiddleware",
]

ROOT_URLCONF = "transdoki.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "billing.context_processors.billing_account",
                "billing.context_processors.billing_banner",
                "billing.context_processors.org_limits",
                "accounts.context_processors.current_org_context",
            ],
        },
    },
]

WSGI_APPLICATION = "transdoki.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

_db_host = os.getenv("DB_HOST", "")
if _db_host:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME", ""),
            "USER": os.getenv("DB_USER", ""),
            "PASSWORD": os.getenv("DB_PASSWORD", ""),
            "HOST": _db_host,
            "PORT": os.getenv("DB_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LOGIN_REDIRECT_URL = "/trips/"

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ru"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

USE_THOUSAND_SEPARATOR = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": True,
    "handlers": {
        "security_file": {
            "level": "WARNING",
            "class": "logging.FileHandler",
            "filename": "logs/security.log",  # 👈 файл для security логов
        },
        "file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": "logs/django.log",  # 👈 общие логи Django
        },
    },
    "loggers": {
        "security": {  # 👈 наш логгер
            "handlers": ["security_file"],
            "level": "WARNING",
            "propagate": False,
        },
        "django": {  # 👈 логи Django
            "handlers": ["file"],
            "level": "INFO",
            "propagate": False,
        },
        "billing": {
            "handlers": ["file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# integrations
PETROLPLUS_AUTH_BASE_URL = os.getenv(
    "PETROLPLUS_AUTH_BASE_URL", os.getenv("PETROLPLUS_BASE_URL")
)
PETROLPLUS_DATA_URL = os.getenv("PETROLPLUS_DATA_URL")
PETROLPLUS_TOKEN_PATH = os.getenv(
    "PETROLPLUS_TOKEN_PATH", "/realms/customers/protocol/openid-connect/token"
)
PETROLPLUS_CLIENT_ID = os.getenv("PETROLPLUS_CLIENT_ID")
PETROLPLUS_CLIENT_SECRET = os.getenv("PETROLPLUS_CLIENT_SECRET")
PETROLPLUS_TIMEOUT = int(os.getenv("PETROLPLUS_TIMEOUT", "15"))

# CloudPayments
CLOUDPAYMENTS_PUBLIC_ID = os.getenv("CLOUDPAYMENTS_PUBLIC_ID", "")
CLOUDPAYMENTS_API_SECRET = os.getenv("CLOUDPAYMENTS_API_SECRET", "")
# Разрешить тестовые платежи (TestMode=1) в production. Только для тестирования интеграции!
CLOUDPAYMENTS_ALLOW_TEST_MODE = os.getenv("CLOUDPAYMENTS_ALLOW_TEST_MODE", "false").lower() == "true"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Email
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",  # в dev — вывод в консоль
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@transdoki.ru")
