# Generated by Django 5.2.11 on 2026-03-16 20:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0008_organization_petrolplus_client_id_and_more'),
        ('persons', '0013_alter_person_phone'),
        ('vehicles', '0007_vehicle_current_odometer_vehicle_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField(editable=False, help_text='Генерируется автоматически в пределах года', verbose_name='Номер')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата')),
                ('year', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='Год')),
                ('status', models.CharField(choices=[('OPEN', 'Открыт'), ('CLOSED', 'Закрыт')], default='OPEN', max_length=10, verbose_name='Статус')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Открыт')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Закрыт')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waybills', to='persons.person', verbose_name='Водитель')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waybills', to='organizations.organization', verbose_name='Организация')),
                ('trailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waybills_of_trailer', to='vehicles.vehicle', verbose_name='Прицеп')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waybills_of_truck', to='vehicles.vehicle', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Путевой лист',
                'verbose_name_plural': 'Путевые листы',
                'ordering': ['-date', '-number'],
            },
        ),
        migrations.CreateModel(
            name='WaybillEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('OUT', 'Выпуск на линию'), ('GIVE', 'Сдача ТС'), ('TAKE', 'Прием ТС'), ('RETURN', 'Возвращение с линии')], max_length=10, verbose_name='Операция')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время')),
                ('odometer', models.PositiveIntegerField(verbose_name='Одометр')),
                ('odometer_delta', models.IntegerField(default=0, editable=False, verbose_name='Δ пробега')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('waybill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='waybills.waybill', verbose_name='Путевой лист')),
            ],
            options={
                'ordering': ['timestamp', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='waybill',
            constraint=models.UniqueConstraint(fields=('created_by', 'year', 'number'), name='unique_waybill_number_per_user_per_year'),
        ),
        migrations.AddIndex(
            model_name='waybillevent',
            index=models.Index(fields=['waybill', 'timestamp'], name='waybills_wa_waybill_c7b9bc_idx'),
        ),
        migrations.AddIndex(
            model_name='waybillevent',
            index=models.Index(fields=['timestamp'], name='waybills_wa_timesta_de8990_idx'),
        ),
    ]
