# Generated by Django 5.2.11 on 2026-03-17 10:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waybillevent',
            name='odometer_delta',
        ),
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_type', models.CharField(choices=[('LOAD', 'Погрузка'), ('UNLOAD', 'Выгрузка')], max_length=10, verbose_name='Тип точки')),
                ('sequence', models.PositiveSmallIntegerField(verbose_name='Порядок')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Адрес')),
                ('odometer', models.PositiveIntegerField(verbose_name='Одометр')),
                ('waybill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_points', to='waybills.waybill', verbose_name='Путевой лист')),
            ],
            options={
                'ordering': ['timestamp', 'id'],
                'indexes': [models.Index(fields=['waybill', 'timestamp'], name='waybills_ro_waybill_d180f2_idx'), models.Index(fields=['point_type', 'timestamp'], name='waybills_ro_point_t_edaf37_idx'), models.Index(fields=['waybill', 'sequence'], name='waybills_ro_waybill_b2f19b_idx')],
                'constraints': [models.UniqueConstraint(fields=('waybill', 'sequence'), name='uniq_route_point_sequence_per_waybill')],
            },
        ),
    ]
