# Generated by Django 5.2.11 on 2026-03-21 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0006_waybill_unique_waybill_number_per_account_per_year'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='waybill',
            name='unique_waybill_number_per_user_per_year',
        ),
    ]
