# Generated by Django 5.2.11 on 2026-03-24 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0026_remove_trip_unique_num_and_date_per_user'),
        ('waybills', '0007_remove_waybill_unique_waybill_number_per_user_per_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='routepoint',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_points', to='trips.trip', verbose_name='Рейс'),
        ),
    ]
