# Generated by Django 5.2.11 on 2026-04-06 14:38

import contracts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_alter_usersession_last_activity'),
        ('organizations', '0023_organization_updated_by_organizationbank_updated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=50, verbose_name='Номер договора')),
                ('contract_type', models.CharField(choices=[('transport', 'Перевозка'), ('supply', 'Поставка'), ('services', 'Услуги'), ('agency', 'Агентский'), ('other', 'Иной')], default='transport', max_length=20, verbose_name='Тип договора')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Действующий'), ('expired', 'Истёк'), ('terminated', 'Расторгнут')], default='draft', max_length=20, verbose_name='Статус')),
                ('date_signed', models.DateField(verbose_name='Дата подписания')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Действует до')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма')),
                ('subject', models.TextField(verbose_name='Предмет договора')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примечания')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts_as_contractor', to='organizations.organization', verbose_name='Контрагент')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('own_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts_as_own', to='organizations.organization', verbose_name='Наша организация')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ['-date_signed', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ContractAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment_type', models.CharField(choices=[('specification', 'Спецификация'), ('addendum', 'Дополнительное соглашение'), ('order_request', 'Договор-заявка')], default='specification', max_length=20, verbose_name='Тип документа')),
                ('number', models.CharField(max_length=50, verbose_name='Номер')),
                ('date_signed', models.DateField(verbose_name='Дата')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма')),
                ('subject', models.TextField(verbose_name='Предмет')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примечания')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='contracts.contract', verbose_name='Договор')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Приложение к договору',
                'verbose_name_plural': 'Приложения к договорам',
                'ordering': ['-date_signed', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('contract', 'Договор'), ('specification', 'Спецификация'), ('addendum', 'Дополнительное соглашение'), ('order_request', 'Договор-заявка')], max_length=20, verbose_name='Тип шаблона')),
                ('file', models.FileField(upload_to=contracts.models.contract_template_upload_to, verbose_name='Файл шаблона')),
                ('uploaded_at', models.DateTimeField(auto_now=True, verbose_name='Дата загрузки')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='Аккаунт')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто загрузил')),
            ],
            options={
                'verbose_name': 'Шаблон документа',
                'verbose_name_plural': 'Шаблоны документов',
            },
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(fields=('account', 'number'), name='unique_contract_number_per_account'),
        ),
        migrations.AlterUniqueTogether(
            name='contracttemplate',
            unique_together={('account', 'template_type')},
        ),
    ]
