# Generated by Django 5.2.11 on 2026-04-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('transport_contract', 'Перевозка (долгосрочный)'), ('single_transport', 'Перевозка (разовый)'), ('order_request', 'Договор-заявка (разовый)'), ('supply_contract', 'Поставка')], default='transport_contract', max_length=30, verbose_name='Тип договора'),
        ),
        migrations.AlterField(
            model_name='contractattachment',
            name='attachment_type',
            field=models.CharField(choices=[('transport_request', 'Заявка на перевозку груза'), ('supply_spec', 'Спецификация')], default='transport_request', max_length=30, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='contracttemplate',
            name='template_type',
            field=models.CharField(choices=[('transport_contract', 'Договор об организации перевозки грузов'), ('transport_request', 'Заявка на перевозку груза'), ('single_transport', 'Договор на перевозку (разовый)'), ('order_request', 'Договор-заявка (разовый)'), ('supply_contract', 'Договор поставки'), ('supply_spec', 'Спецификация')], max_length=30, verbose_name='Тип шаблона'),
        ),
    ]
