# Generated by Django 5.2.8 on 2025-11-08 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200, verbose_name='Наименование банка')),
                ('bic', models.CharField(max_length=9, unique=True, verbose_name='БИК')),
                ('corr_account', models.CharField(max_length=20, verbose_name='Корреспондентский счёт')),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Полное наименование')),
                ('short_name', models.CharField(max_length=200, verbose_name='Сокращённое наименование')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП')),
                ('ogrn', models.CharField(max_length=15, unique=True, verbose_name='ОГРН')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес юридического лица')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='OrganizationBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_num', models.CharField(max_length=20, verbose_name='Расчётный счёт')),
                ('account_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.bank', verbose_name='Банк')),
                ('account_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='organizations.organization', verbose_name='Владелец счёта')),
            ],
            options={
                'verbose_name': 'Банковский счёт организации',
                'verbose_name_plural': 'Банковские счета организаций',
                'constraints': [models.UniqueConstraint(fields=('account_num', 'account_bank'), name='unique_account_bank')],
            },
        ),
    ]
