# Generated by Django 5.2.8 on 2025-11-09 08:17

import organizations.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='inn',
            field=models.CharField(max_length=12, unique=True, validators=[organizations.validators.validate_inn], verbose_name='ИНН'),
        ),
    ]
