# Generated by Django 5.2.8 on 2025-11-13 15:36

from django.db import migrations, models

import organizations.validators


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organization_unique_inn_per_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='inn',
            field=models.CharField(max_length=12, validators=[organizations.validators.validate_inn], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='ogrn',
            field=models.CharField(max_length=15, verbose_name='ОГРН'),
        ),
    ]
