# Generated by Django 5.2.8 on 2025-11-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_organization_inn_alter_organization_ogrn'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_own_company',
            field=models.BooleanField(default=False, verbose_name='Моя компания'),
        ),
    ]
