# Generated by Django 5.2.11 on 2026-03-16 20:16

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_organization_is_own_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='petrolplus_client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='petrolplus_client_secret',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=512, null=True)),
        ),
        migrations.AddField(
            model_name='organization',
            name='petrolplus_credentials_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='petrolplus_integration_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
