# Generated by Django 5.2.11 on 2026-03-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_organization_petrolplus_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='petrolplus_integration_enabled',
            field=models.BooleanField(default=False, verbose_name='Подключить интеграцию'),
        ),
    ]
