# Generated by Django 5.2.11 on 2026-03-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_alter_organization_petrolplus_integration_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='petrolplus_integration_enabled',
            field=models.BooleanField(default=False, verbose_name='GPC (Джи Пи Си)'),
        ),
    ]
