# Generated by Django 5.2.11 on 2026-03-21 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_role_account_userprofile_account_and_more'),
        ('organizations', '0011_alter_organization_petrolplus_integration_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account'),
        ),
        migrations.AddField(
            model_name='organizationbank',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account'),
        ),
    ]
