# Generated by Django 5.2.11 on 2026-03-21 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_account_and_profiles'),
        ('organizations', '0014_backfill_account_retry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='organizationbank',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account'),
        ),
    ]
