# Generated by Django 5.2.11 on 2026-03-21 18:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_account_and_profiles'),
        ('organizations', '0015_alter_organization_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('account', 'inn'), name='unique_inn_per_account'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(condition=models.Q(('is_own_company', True)), fields=('inn',), name='unique_own_company_inn_global'),
        ),
    ]
