# Generated by Django 5.2.11 on 2026-03-21 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0016_organization_unique_inn_per_account_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organization',
            name='unique_inn_per_user',
        ),
    ]
