# Generated by Django 5.2.11 on 2026-03-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_alter_organization_ogrn'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='director_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='ФИО руководителя'),
        ),
        migrations.AddField(
            model_name='organization',
            name='director_title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Должность руководителя'),
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='organization',
            name='postal_address',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Почтовый адрес'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Юридический адрес'),
        ),
    ]
