# Generated by Django 5.2.11 on 2026-03-30 08:42

from django.db import migrations


def migrate_contacts_forward(apps, schema_editor):
    Person = apps.get_model("persons", "Person")
    OrganizationContact = apps.get_model("organizations", "OrganizationContact")

    contacts = Person.objects.filter(role="contact", employer__isnull=False)
    for person in contacts:
        full_name = f"{person.surname} {person.name}"
        if person.patronymic:
            full_name += f" {person.patronymic}"

        OrganizationContact.objects.create(
            organization=person.employer,
            name=full_name.strip(),
            phone=person.phone or "",
            position=person.position or "",
            created_by=person.created_by,
            account=person.account,
        )


def migrate_contacts_backward(apps, schema_editor):
    # Обратная миграция не восстанавливает Person — данные сохранены в OrganizationContact
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0020_add_organization_contact"),
        ("persons", "0022_person_position_person_role"),
    ]

    operations = [
        migrations.RunPython(migrate_contacts_forward, migrate_contacts_backward),
    ]
