# Generated by Django 5.2.11 on 2026-04-08 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_usersession_last_activity'),
        ('organizations', '0023_organization_updated_by_organizationbank_updated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='organization',
            name='unique_inn_per_account',
            constraint=models.UniqueConstraint(fields=('account', 'inn'), name='unique_inn_per_account', violation_error_message='Организация с таким ИНН уже существует.'),
        ),
        migrations.AlterConstraint(
            model_name='organization',
            name='unique_own_company_inn_global',
            constraint=models.UniqueConstraint(condition=models.Q(('is_own_company', True)), fields=('inn',), name='unique_own_company_inn_global', violation_error_message='Компания с таким ИНН уже зарегистрирована в системе.'),
        ),
    ]
