# Generated by Django 5.2.8 on 2025-11-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='max_own_companies',
            field=models.PositiveIntegerField(default=1, verbose_name='Лимит собственных компаний'),
        ),
    ]
