# Generated by Django 5.2.11 on 2026-03-21 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_max_own_companies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('dispatcher', 'Dispatcher'), ('logist', 'Logist')], default='owner', max_length=20, verbose_name='Роль'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название аккаунта')),
                ('max_sessions', models.PositiveIntegerField(default=1, verbose_name='Лимит одновременных сессий аккаунта')),
                ('max_own_companies', models.PositiveIntegerField(default=1, verbose_name='Лимит собственных компаний аккаунта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Владелец аккаунта')),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
                'db_table': 'accounts_account',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='accounts.account', verbose_name='Аккаунт'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['account', 'role'], name='accounts_us_account_5ef021_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_active'], name='accounts_ac_is_acti_b52bc0_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['owner', 'is_active'], name='accounts_ac_owner_i_8fab56_idx'),
        ),
    ]
