# Generated by Django 5.2.11 on 2026-03-21 17:17

from django.db import migrations

BATCH_SIZE = 1000


def backfill_accounts(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("accounts", "UserProfile")
    Account = apps.get_model("accounts", "Account")

    created_accounts = 0
    linked_profiles = 0
    updated_roles = 0
    updated_owners = 0

    users_qs = User.objects.all().only("id", "username", "is_active")
    for user in users_qs.iterator(chunk_size=BATCH_SIZE):
        profile, _ = UserProfile.objects.get_or_create(
            user_id=user.id,
            defaults={
                "max_sessions": 1,
                "max_own_companies": 1,
                "role": "owner",
            },
        )

        account = None

        # Если профиль уже привязан — используем его account
        if profile.account_id:
            account = Account.objects.filter(id=profile.account_id).first()
        else:
            # Ищем аккаунт, где пользователь owner
            account = Account.objects.filter(owner_id=user.id).order_by("id").first()

            # Если нет — создаём
            if account is None:
                account = Account.objects.create(
                    name=(user.username or f"user_{user.id}"),
                    owner_id=user.id,
                    max_sessions=profile.max_sessions or 1,
                    max_own_companies=profile.max_own_companies or 1,
                    is_active=user.is_active,
                )
                created_accounts += 1

            # Привязываем профиль к account
            profile.account_id = account.id
            profile.role = "owner"  # исторически все текущие пользователи считаются owner
            profile.save(update_fields=["account", "role"])
            linked_profiles += 1

        # Если account есть, но owner пустой — заполняем
        if account and account.owner_id is None:
            account.owner_id = user.id
            account.save(update_fields=["owner"])
            updated_owners += 1

        # Если профиль уже был привязан, но role не owner — выставляем owner
        if profile.role != "owner":
            profile.role = "owner"
            profile.save(update_fields=["role"])
            updated_roles += 1

    left_unlinked = UserProfile.objects.filter(account_id__isnull=True).count()
    print(
        f"[accounts backfill] created_accounts={created_accounts}, "
        f"linked_profiles={linked_profiles}, updated_roles={updated_roles}, "
        f"updated_owners={updated_owners}, left_unlinked_profiles={left_unlinked}"
    )


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("accounts", "0003_userprofile_role_account_userprofile_account_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_accounts, migrations.RunPython.noop),
    ]