# Generated by Django 5.2.11 on 2026-03-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_account_and_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='max_own_companies',
            field=models.PositiveIntegerField(default=1, verbose_name='(Legacy) Лимит собственных компаний'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='max_sessions',
            field=models.PositiveIntegerField(default=1, verbose_name='(Legacy) Лимит одновременных сессий'),
        ),
    ]
