# Generated by Django 5.2.11 on 2026-03-22 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_max_own_companies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='max_own_companies',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='max_sessions',
        ),
    ]
