# Generated by Django 5.2.11 on 2026-03-23 09:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userprofile_max_own_companies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='max_own_companies',
        ),
        migrations.RemoveField(
            model_name='account',
            name='max_sessions',
        ),
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Баланс (₽)'),
        ),
        migrations.AddField(
            model_name='account',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('-500.00'), help_text='Баланс ниже этого значения блокирует создание новых сущностей', max_digits=10, verbose_name='Кредитный лимит (₽)'),
        ),
        migrations.AddField(
            model_name='account',
            name='free_orgs',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Бесплатных компаний'),
        ),
        migrations.AddField(
            model_name='account',
            name='free_users',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Бесплатных пользователей'),
        ),
        migrations.AddField(
            model_name='account',
            name='free_vehicles',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Бесплатных машин'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_billing_exempt',
            field=models.BooleanField(default=False, help_text='Аккаунт не тарифицируется и не блокируется по балансу', verbose_name='Освобождён от биллинга'),
        ),
    ]
