# Generated by Django 5.2.11 on 2026-03-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_billing_core'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('owner', 'Владелец'), ('admin', 'Администратор'), ('dispatcher', 'Диспетчер'), ('logist', 'Логист')], default='owner', max_length=20, verbose_name='Роль'),
        ),
    ]
