# Generated by Django 5.2.11 on 2026-03-29 13:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cached_daily_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Обновляется командой charge_daily', max_digits=10, verbose_name='Суточная стоимость (кеш)'),
        ),
    ]
