# Generated by Django 5.2.11 on 2026-04-15 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_usersession_last_activity'),
        ('organizations', '0024_alter_organization_unique_inn_per_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_active_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organizations.organization', verbose_name='Последняя активная своя фирма'),
        ),
    ]
