# Generated by Django 5.2.11 on 2026-04-08 07:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_alter_usersession_last_activity'),
        ('organizations', '0023_organization_updated_by_organizationbank_updated_by_and_more'),
        ('trips', '0043_trip_updated_by_tripattachment_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=50, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('payment_due', models.DateField(blank=True, null=True, verbose_name='Оплатить до')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Выставлен'), ('paid', 'Оплачен'), ('cancelled', 'Аннулирован')], db_index=True, default='draft', max_length=20, verbose_name='Статус')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='organizations.organization', verbose_name='Заказчик')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Счёт',
                'verbose_name_plural': 'Счета',
                'ordering': ['-date', '-number'],
            },
        ),
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=50, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('signed', 'Подписан'), ('cancelled', 'Аннулирован')], db_index=True, default='draft', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(verbose_name='Наименование услуги')),
                ('amount_net', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма без НДС')),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма НДС')),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма с НДС')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='act', to='invoicing.invoice', verbose_name='Счёт')),
            ],
            options={
                'verbose_name': 'Акт',
                'verbose_name_plural': 'Акты',
                'ordering': ['-date', '-number'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('service', 'Услуга'), ('penalty', 'Штраф')], max_length=20, verbose_name='Тип')),
                ('description', models.CharField(max_length=255, verbose_name='Наименование')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена без НДС')),
                ('discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Скидка %')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Скидка ₽')),
                ('vat_rate', models.IntegerField(choices=[(0, 'Без НДС'), (10, '10%'), (20, '20%')], default=0, verbose_name='Ставка НДС')),
                ('amount_net', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Сумма без НДС')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Сумма НДС')),
                ('amount_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Сумма с НДС')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoicing.invoice', verbose_name='Счёт')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='trips.trip', verbose_name='Рейс')),
            ],
            options={
                'verbose_name': 'Строка счёта',
                'verbose_name_plural': 'Строки счёта',
                'ordering': ['pk'],
            },
        ),
    ]
