# Generated by Django 5.2.11 on 2026-04-09 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
        ('organizations', '0024_alter_organization_unique_inn_per_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='organizations.organizationbank', verbose_name='Банковский счёт'),
        ),
    ]
