# Generated by Django 5.2.11 on 2026-04-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_payment_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='direction',
            field=models.CharField(choices=[('incoming', 'Поступление'), ('outgoing', 'Списание')], default='incoming', max_length=20, verbose_name='Направление'),
        ),
    ]
