# Generated by Django 5.2.11 on 2026-04-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_payment_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='vat_rate',
            field=models.IntegerField(blank=True, choices=[(0, '0%'), (5, '5%'), (7, '7%'), (10, '10%'), (22, '22%')], null=True, verbose_name='Ставка НДС'),
        ),
    ]
