# Generated by Django 5.2.11 on 2026-04-10 15:57

from django.db import migrations


def convert_zero_to_null(apps, schema_editor):
    InvoiceLine = apps.get_model("invoicing", "InvoiceLine")
    InvoiceLine.objects.filter(vat_rate=0).update(vat_rate=None)


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0006_vat_rate_nullable'),
    ]

    operations = [
        migrations.RunPython(convert_zero_to_null, migrations.RunPython.noop),
    ]
