# Generated by Django 5.2.11 on 2026-04-11 12:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0007_convert_vat_zero_to_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='unit',
            field=models.CharField(choices=[('усл.', 'усл.'), ('рейс', 'рейс'), ('т', 'т'), ('км', 'км'), ('ч', 'ч')], default='усл.', max_length=10, verbose_name='Ед. изм.'),
        ),
    ]
