# Generated by Django 5.2.11 on 2026-04-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0009_invoicing_rework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='description',
            field=models.CharField(max_length=350, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.CharField(blank=True, default='', max_length=350, verbose_name='Комментарий'),
        ),
    ]
