# Generated by Django 5.2.11 on 2026-04-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0010_alter_invoiceline_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='description',
            field=models.TextField(max_length=350, verbose_name='Наименование услуги'),
        ),
    ]
