# Generated by Django 5.2.11 on 2026-04-15 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0011_alter_act_description'),
        ('organizations', '0024_alter_organization_unique_inn_per_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='seller',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_own_company': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_as_seller', to='organizations.organization', verbose_name='Поставщик (наша фирма)'),
        ),
    ]
