# Generated by Django 5.2.11 on 2026-04-15 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile_last_active_org'),
        ('invoicing', '0013_backfill_invoice_seller'),
        ('organizations', '0024_alter_organization_unique_inn_per_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoice',
            name='uniq_invoice_account_year_number',
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('seller', 'year', 'number'), name='uniq_invoice_seller_year_number'),
        ),
    ]
