# Generated by Django 5.2.11 on 2026-04-15 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0014_remove_invoice_uniq_invoice_account_year_number_and_more'),
        ('organizations', '0024_alter_organization_unique_inn_per_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='seller',
            field=models.ForeignKey(limit_choices_to={'is_own_company': True}, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_as_seller', to='organizations.organization', verbose_name='Поставщик (наша фирма)'),
        ),
    ]
