# Generated by Django 5.2.11 on 2026-04-06 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_alter_usersession_last_activity'),
        ('organizations', '0023_organization_updated_by_organizationbank_updated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelCardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('petrolplus', 'PetrolPlus')], max_length=20, verbose_name='Провайдер')),
                ('external_id', models.CharField(db_index=True, max_length=100, verbose_name='ID транзакции в системе провайдера')),
                ('card_number', models.CharField(max_length=50, verbose_name='Номер карты')),
                ('holder_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Держатель карты')),
                ('fuel_type', models.CharField(max_length=100, verbose_name='Тип топлива (оригинал из API)')),
                ('litres', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Объём (л)')),
                ('price_per_litre', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Цена за литр')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма списания')),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='НДС')),
                ('timestamp', models.DateTimeField(verbose_name='Дата и время операции')),
                ('station_name', models.CharField(blank=True, default='', max_length=300, verbose_name='АЗС')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Сырые данные API')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_card_transactions', to='organizations.organization', verbose_name='Организация (договор)')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Транзакция по топливной карте',
                'verbose_name_plural': 'Транзакции по топливным картам',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['organization', 'timestamp'], name='integration_organiz_6a830e_idx')],
                'constraints': [models.UniqueConstraint(fields=('account', 'provider', 'external_id'), name='unique_fuel_card_transaction')],
            },
        ),
    ]
