# Generated by Django 5.2.8 on 2025-11-09 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_organization_inn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn', models.CharField(max_length=20, unique=True, verbose_name='Регистрационный номер')),
                ('brand', models.CharField(blank=True, max_length=20, verbose_name='Марка')),
                ('model', models.CharField(blank=True, max_length=20, verbose_name='Модель')),
                ('vehicle_type', models.CharField(choices=[('single', 'Грузовик одиночный'), ('truck', 'Тягач седельный'), ('trailer', 'Прицеп')], max_length=10, verbose_name='Тип ТС')),
            ],
            options={
                'verbose_name': 'Транспортное средство',
                'verbose_name_plural': 'Транспортные средства',
            },
        ),
        migrations.CreateModel(
            name='VehicleOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('property', 'Собственность'), ('coproperty', 'Совместная собственность супругов'), ('rent', 'Аренда'), ('leasing', 'Лизинг'), ('unpaid', 'Безвозмездное пользование')], max_length=10, verbose_name='Тип владения')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Cобственник ТС')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle', verbose_name='Машина')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('vehicle', 'owner'), name='unique_vehicle_owner')],
            },
        ),
    ]
