# Generated by Django 5.2.8 on 2025-11-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehicle_unique_grn_per_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='grn',
            field=models.CharField(max_length=20, verbose_name='Регистрационный номер'),
        ),
    ]
