# Generated by Django 5.2.8 on 2025-11-23 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_organization_is_own_company'),
        ('vehicles', '0005_alter_vehicle_grn'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Cобственник ТС'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='property_type',
            field=models.CharField(choices=[('property', 'Собственность'), ('coproperty', 'Совместная собственность супругов'), ('rent', 'Аренда'), ('leasing', 'Лизинг'), ('unpaid', 'Безвозмездное пользование')], default='property', max_length=10, verbose_name='Тип владения'),
        ),
        migrations.DeleteModel(
            name='VehicleOrganisation',
        ),
    ]
