# Generated by Django 5.2.11 on 2026-03-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_vehicle_owner_vehicle_property_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='current_odometer',
            field=models.PositiveIntegerField(default=0, verbose_name='Текущий одометр'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('AT_PARK', 'В парке'), ('ON_LINE', 'На линии'), ('TRANSFER', 'Пересмена')], default='AT_PARK', max_length=20, verbose_name='Статус'),
        ),
    ]
