# Generated by Django 5.2.11 on 2026-03-21 18:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_account_and_profiles'),
        ('organizations', '0016_organization_unique_inn_per_account_and_more'),
        ('vehicles', '0010_alter_vehicle_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('account', 'grn'), name='unique_grn_per_account'),
        ),
    ]
