# Generated by Django 5.2.11 on 2026-03-21 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0011_vehicle_unique_grn_per_account'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vehicle',
            name='unique_grn_per_user',
        ),
    ]
