# Generated by Django 5.2.11 on 2026-03-29 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_alter_organization_ogrn'),
        ('vehicles', '0012_remove_vehicle_unique_grn_per_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='organizations.organization', verbose_name='Cобственник ТС'),
        ),
    ]
