# Generated by Django 5.2.11 on 2026-04-03 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_usersession_last_activity'),
        ('vehicles', '0015_vehicle_updated_by'),
        ('waybills', '0010_waybill_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleFueling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('manual', 'Ручной ввод'), ('fuel_card', 'Топливная карта')], default='manual', max_length=20, verbose_name='Источник данных')),
                ('fuel_type', models.CharField(choices=[('diesel', 'ДТ'), ('ai_92', 'АИ-92'), ('ai_95', 'АИ-95'), ('ai_98', 'АИ-98'), ('cng', 'Метан (CNG)'), ('lpg', 'Пропан (LPG)'), ('adblue', 'AdBlue')], max_length=10, verbose_name='Тип топлива')),
                ('litres', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Объём (л)')),
                ('price_per_litre', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена за литр')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость')),
                ('timestamp', models.DateTimeField(verbose_name='Дата и время заправки')),
                ('station_name', models.CharField(blank=True, default='', max_length=200, verbose_name='АЗС')),
                ('external_id', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Внешний ID транзакции')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Сырые данные API')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuelings', to='vehicles.vehicle', verbose_name='Транспортное средство')),
                ('waybill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuelings', to='waybills.waybill', verbose_name='Путевой лист')),
            ],
            options={
                'verbose_name': 'Заправка',
                'verbose_name_plural': 'Заправки',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['vehicle', 'timestamp'], name='vehicles_ve_vehicle_18a310_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('vehicle', 'source', 'external_id'), name='unique_fueling_external_id')],
            },
        ),
    ]
