# Generated by Django 5.2.8 on 2025-11-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_alter_person_name_alter_person_patronymic_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Человек', 'verbose_name_plural': 'Люди'},
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('surname', 'name', 'patronymic'), name='unique_person_full_name'),
        ),
    ]
