# Generated by Django 5.2.8 on 2025-11-13 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_remove_person_unique_person_full_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='person',
            name='unique_fio_per_user',
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('surname', 'name', 'patronymic', 'created_by'), name='unique_fio_per_user'),
        ),
    ]
