# Generated by Django 5.2.8 on 2025-11-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0007_person_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, default='70000000000', max_length=12, null=True, verbose_name='Номер телефона'),
        ),
    ]
