# Generated by Django 5.2.8 on 2025-11-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0010_alter_person_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Номер телефона'),
        ),
    ]
