# Generated by Django 5.2.8 on 2025-11-22 12:43

import persons.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0012_alter_person_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=25, validators=[persons.validators.validate_phone_number], verbose_name='Номер телефона'),
        ),
    ]
