# Generated by Django 5.2.11 on 2026-03-21 18:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_account_and_profiles'),
        ('persons', '0016_alter_person_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('surname', 'name', 'patronymic', 'account'), name='unique_fio_per_account'),
        ),
    ]
