# Generated by Django 5.2.11 on 2026-03-21 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0017_person_unique_fio_per_account'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='person',
            name='unique_fio_per_user',
        ),
    ]
