# Generated by Django 5.2.11 on 2026-03-26 08:52

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0018_remove_person_unique_fio_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=django_cryptography.fields.encrypt(models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
        ),
        migrations.AddField(
            model_name='person',
            name='is_own_employee',
            field=models.BooleanField(default=False, help_text='Сотрудник одной из ваших организаций', verbose_name='Штатный сотрудник'),
        ),
        migrations.AddField(
            model_name='person',
            name='license_categories',
            field=models.CharField(blank=True, help_text='Например: B, C, CE', max_length=20, verbose_name='Категории ВУ'),
        ),
        migrations.AddField(
            model_name='person',
            name='license_expiry_date',
            field=django_cryptography.fields.encrypt(models.DateField(blank=True, null=True, verbose_name='ВУ действует до')),
        ),
        migrations.AddField(
            model_name='person',
            name='license_issued_date',
            field=django_cryptography.fields.encrypt(models.DateField(blank=True, null=True, verbose_name='Дата выдачи ВУ')),
        ),
        migrations.AddField(
            model_name='person',
            name='license_number',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=10, verbose_name='Номер ВУ')),
        ),
        migrations.AddField(
            model_name='person',
            name='passport_department_code',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=7, verbose_name='Код подразделения')),
        ),
        migrations.AddField(
            model_name='person',
            name='passport_issued_by',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, verbose_name='Кем выдан')),
        ),
        migrations.AddField(
            model_name='person',
            name='passport_issued_date',
            field=django_cryptography.fields.encrypt(models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта')),
        ),
        migrations.AddField(
            model_name='person',
            name='passport_number',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=6, verbose_name='Номер паспорта')),
        ),
        migrations.AddField(
            model_name='person',
            name='passport_series',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=4, verbose_name='Серия паспорта')),
        ),
    ]
