# Generated by Django 5.2.11 on 2026-03-29 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_alter_organization_ogrn'),
        ('persons', '0019_person_employee_flag_passport_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organizations.organization', verbose_name='Работодатель'),
        ),
    ]
