# Generated by Django 5.2.11 on 2026-03-29 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0020_person_employer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='is_own_employee',
        ),
    ]
