# Generated by Django 5.2.11 on 2026-03-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0021_remove_is_own_employee_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('driver', 'Водитель'), ('contact', 'Контактное лицо')], default='driver', max_length=20, verbose_name='Роль'),
        ),
    ]
