# Generated by Django 5.2.11 on 2026-03-30 08:50

from django.db import migrations


def delete_contact_persons(apps, schema_editor):
    """Удаляем записи Person с role='contact' — данные уже перенесены в OrganizationContact."""
    Person = apps.get_model("persons", "Person")
    Person.objects.filter(role="contact").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0022_person_position_person_role"),
        ("organizations", "0021_migrate_contacts_from_person"),
    ]

    operations = [
        migrations.RunPython(delete_contact_persons, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="person",
            name="position",
        ),
        migrations.RemoveField(
            model_name="person",
            name="role",
        ),
    ]
