# Generated by Django 5.2.8 on 2025-11-09 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_organization_inn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_trip', models.PositiveSmallIntegerField(verbose_name='Номер заявки')),
                ('date_of_trip', models.DateField(blank=True, null=True, verbose_name='Дата заявки')),
                ('planned_loading_date', models.DateTimeField(verbose_name='Заявленные дата и время погрузки')),
                ('planned_unloading_date', models.DateTimeField(verbose_name='Заявленные дата и время выгрузки')),
                ('actual_loading_date', models.DateTimeField(blank=True, null=True, verbose_name='Фактическая дата и время погрузки')),
                ('actual_unloading_date', models.DateTimeField(blank=True, null=True, verbose_name='Фактическая дата и время выгрузки')),
                ('cargo', models.CharField(max_length=20, verbose_name='Груз')),
                ('weight', models.PositiveIntegerField(verbose_name='Вес')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips_as_carrier', to='organizations.organization', verbose_name='Перевозчик')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips_as_client', to='organizations.organization', verbose_name='Заказчик перевозки')),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips_as_consignee', to='organizations.organization', verbose_name='Получатель')),
                ('consignor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips_as_consignor', to='organizations.organization', verbose_name='Отправитель')),
            ],
        ),
    ]
