# Generated by Django 5.2.8 on 2025-11-09 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_alter_person_options_person_unique_person_full_name'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='trips_as_driver', to='persons.person', verbose_name='Водитель'),
            preserve_default=False,
        ),
    ]
