# Generated by Django 5.2.8 on 2025-11-09 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_driver'),
        ('vehicles', '0002_alter_vehicle_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trailer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='trips_as_trailer', to='vehicles.vehicle', verbose_name='Прицеп'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='truck',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='trips_as_truck', to='vehicles.vehicle', verbose_name='Автомобиль'),
            preserve_default=False,
        ),
    ]
