# Generated by Django 5.2.8 on 2025-11-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_trailer_trip_truck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес'),
        ),
    ]
