# Generated by Django 5.2.8 on 2025-11-13 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_organization_inn_alter_organization_ogrn'),
        ('persons', '0006_remove_person_unique_fio_per_user_and_more'),
        ('trips', '0005_trip_created_at_trip_created_by_trip_updated_at'),
        ('vehicles', '0005_alter_vehicle_grn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'verbose_name': 'Рейс', 'verbose_name_plural': 'Рейсы'},
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.UniqueConstraint(fields=('created_by', 'num_of_trip', 'date_of_trip'), name='unique_num_and_date_per_user'),
        ),
    ]
