# Generated by Django 5.2.8 on 2025-11-26 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_alter_trip_options_trip_unique_num_and_date_per_user'),
        ('vehicles', '0006_vehicle_owner_vehicle_property_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips_as_trailer', to='vehicles.vehicle', verbose_name='Прицеп'),
        ),
    ]
