# Generated by Django 5.2.8 on 2025-11-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_alter_trip_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='carrier_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Общая стоимость заказа для перевозчика', max_digits=12, null=True, verbose_name='Стоимость перевозки'),
        ),
        migrations.AddField(
            model_name='trip',
            name='client_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Общая стоимость заказа для клиента', max_digits=12, null=True, verbose_name='Стоимость заказа'),
        ),
        migrations.AddField(
            model_name='trip',
            name='comments',
            field=models.TextField(blank=True, help_text='Дополнительная информация о рейсе', max_length=1000, verbose_name='Комментарии'),
        ),
    ]
