# Generated by Django 5.2.8 on 2025-11-26 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_trip_carrier_cost_trip_client_cost_trip_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='carrier_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Общая стоимость заказа для перевозчика', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость перевозки'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='client_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Общая стоимость заказа для клиента', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость заказа'),
        ),
    ]
