# Generated by Django 5.2.8 on 2025-11-26 15:30

import trips.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_alter_trip_carrier_cost_alter_trip_client_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='carrier_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Общая стоимость заказа для перевозчика', max_digits=12, null=True, validators=[trips.validators.RussianMinValueValidator(0.01)], verbose_name='Стоимость перевозки'),
        ),
    ]
