# Generated by Django 5.2.8 on 2025-11-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0014_alter_trip_carrier_cost_alter_trip_client_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='loading_type',
            field=models.CharField(blank=True, choices=[('rear', 'Задняя'), ('top', 'Верхняя'), ('side', 'Боковая')], default='', max_length=20, verbose_name='Тип погрузки'),
        ),
        migrations.AddField(
            model_name='trip',
            name='payment_condition',
            field=models.CharField(blank=True, choices=[('documents', 'По факту предоставления документов'), ('unloading', 'По факту выгрузки')], default='', max_length=50, verbose_name='Условия оплаты'),
        ),
        migrations.AddField(
            model_name='trip',
            name='payment_term',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Срок оплаты'),
        ),
        migrations.AddField(
            model_name='trip',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('cashless', 'Безналичный расчёт'), ('cash', 'Наличный расчёт')], default='', max_length=50, verbose_name='Форма оплаты'),
        ),
        migrations.AddField(
            model_name='trip',
            name='unloading_type',
            field=models.CharField(blank=True, choices=[('rear', 'Задняя'), ('top', 'Верхняя'), ('side', 'Боковая')], default='', max_length=20, verbose_name='Тип выгрузки'),
        ),
    ]
