# Generated by Django 5.2.11 on 2026-03-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0015_trip_loading_type_trip_payment_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='loading_address',
            field=models.CharField(default='Адрес не указан', max_length=200, verbose_name='Адрес погрузки'),
        ),
        migrations.AddField(
            model_name='trip',
            name='unloading_address',
            field=models.CharField(default='Адрес не указан', max_length=200, verbose_name='Адрес выгрузки'),
        ),
    ]
