# Generated by Django 5.2.11 on 2026-03-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0016_trip_loading_address_trip_unloading_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='loading_address',
            field=models.CharField(max_length=200, verbose_name='Адрес погрузки'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='unloading_address',
            field=models.CharField(max_length=200, verbose_name='Адрес выгрузки'),
        ),
    ]
