# Generated by Django 5.2.11 on 2026-03-06 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0013_alter_person_phone'),
        ('trips', '0017_alter_trip_loading_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(choices=[('loading', 'Погрузка'), ('unloading', 'Выгрузка')], max_length=16, verbose_name='Тип контакта')),
                ('raw_name', models.CharField(help_text='Например: "Ольга зоотехник"', max_length=255, verbose_name='Контакт')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_contacts', to='persons.person', verbose_name='Person (опционально)')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='trips.trip', verbose_name='Рейс')),
            ],
            options={
                'verbose_name': 'Контакт рейса',
                'verbose_name_plural': 'Контакты рейса',
                'ordering': ('trip_id', 'point', 'order', 'id'),
                'indexes': [models.Index(fields=['trip', 'point'], name='trips_tripc_trip_id_d7f709_idx')],
            },
        ),
    ]
