# Generated by Django 5.2.11 on 2026-03-06 11:14

import persons.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0018_tripcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='loading_contact_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Контакт на погрузке (имя)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='loading_contact_phone',
            field=models.CharField(blank=True, default='', max_length=25, validators=[persons.validators.validate_phone_number], verbose_name='Контакт на погрузке (телефон)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='unloading_contact_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Контакт на выгрузке (имя)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='unloading_contact_phone',
            field=models.CharField(blank=True, default='', max_length=25, validators=[persons.validators.validate_phone_number], verbose_name='Контакт на выгрузке (телефон)'),
        ),
        migrations.DeleteModel(
            name='TripContact',
        ),
    ]
