# Generated by Django 5.2.11 on 2026-03-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0019_trip_loading_contact_name_trip_loading_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='num_of_trip',
            field=models.PositiveSmallIntegerField(editable=False, verbose_name='Номер заявки'),
        ),
    ]
