# Generated by Django 5.2.11 on 2026-03-21 18:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_account_and_profiles'),
        ('organizations', '0016_organization_unique_inn_per_account_and_more'),
        ('persons', '0017_person_unique_fio_per_account'),
        ('trips', '0024_alter_trip_account_alter_tripattachment_account'),
        ('vehicles', '0010_alter_vehicle_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.UniqueConstraint(fields=('account', 'num_of_trip', 'date_of_trip'), name='unique_num_and_date_per_account'),
        ),
    ]
