# Generated by Django 5.2.11 on 2026-03-21 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0025_trip_unique_num_and_date_per_account'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trip',
            name='unique_num_and_date_per_user',
        ),
    ]
