# Generated by Django 5.2.11 on 2026-03-24 09:59

import django.db.models.deletion
import persons.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0026_remove_trip_unique_num_and_date_per_user'),
        ('waybills', '0008_routepoint_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_type', models.CharField(choices=[('LOAD', 'Погрузка'), ('UNLOAD', 'Выгрузка')], max_length=10, verbose_name='Тип точки')),
                ('sequence', models.PositiveSmallIntegerField(help_text='Хронологический порядок точек внутри рейса', verbose_name='Порядковый номер')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('planned_date', models.DateTimeField(verbose_name='Заявленные дата и время')),
                ('actual_date', models.DateTimeField(blank=True, null=True, verbose_name='Фактические дата и время')),
                ('contact_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Контакт (имя)')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=25, validators=[persons.validators.validate_phone_number], verbose_name='Контакт (телефон)')),
                ('loading_type', models.CharField(blank=True, choices=[('rear', 'Задняя'), ('top', 'Верхняя'), ('side', 'Боковая')], default='', max_length=20, verbose_name='Тип погрузки/выгрузки')),
                ('odometer', models.PositiveIntegerField(blank=True, help_text='Показание одометра путевого листа в момент погрузки/выгрузки', null=True, verbose_name='Показание одометра')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='trips.trip', verbose_name='Рейс')),
                ('waybill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_points', to='waybills.waybill', verbose_name='Путевой лист')),
            ],
            options={
                'verbose_name': 'Точка маршрута рейса',
                'verbose_name_plural': 'Точки маршрута рейса',
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('trip', 'sequence'), name='unique_trippoint_sequence_per_trip')],
            },
        ),
    ]
