# Generated by Django 5.2.11 on 2026-03-24 10:08

from django.db import migrations


def populate_trippoints(apps, schema_editor):
    """
    Переносит плоские поля погрузки/выгрузки из Trip в TripPoint.
    Для каждого рейса создаёт две точки:
      sequence=1, type=LOAD  — из полей loading_*
      sequence=2, type=UNLOAD — из полей unloading_*
    Плоские поля Trip не трогаются (legacy до явного удаления).
    """
    Trip = apps.get_model("trips", "Trip")
    TripPoint = apps.get_model("trips", "TripPoint")

    points_to_create = []

    for trip in Trip.objects.all():
        # Точка погрузки
        points_to_create.append(
            TripPoint(
                trip=trip,
                point_type="LOAD",
                sequence=1,
                address=trip.loading_address or "",
                planned_date=trip.planned_loading_date,
                actual_date=trip.actual_loading_date,
                contact_name=trip.loading_contact_name or "",
                contact_phone=trip.loading_contact_phone or "",
                loading_type=trip.loading_type or "",
            )
        )
        # Точка выгрузки
        points_to_create.append(
            TripPoint(
                trip=trip,
                point_type="UNLOAD",
                sequence=2,
                address=trip.unloading_address or "",
                planned_date=trip.planned_unloading_date,
                actual_date=trip.actual_unloading_date,
                contact_name=trip.unloading_contact_name or "",
                contact_phone=trip.unloading_contact_phone or "",
                loading_type=trip.unloading_type or "",
            )
        )

    TripPoint.objects.bulk_create(points_to_create)


def reverse_populate_trippoints(apps, schema_editor):
    """
    Откат: удаляет все TripPoint с sequence 1 и 2,
    созданные этой миграцией.
    """
    TripPoint = apps.get_model("trips", "TripPoint")
    TripPoint.objects.filter(sequence__in=[1, 2]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0027_add_trippoint"),
    ]

    operations = [
        migrations.RunPython(
            populate_trippoints,
            reverse_code=reverse_populate_trippoints,
        ),
    ]
