# Generated by Django 5.2.11 on 2026-03-25 12:42

import trips.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0029_remove_flat_loading_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='trip',
            name='carrier_cost_unit',
            field=models.CharField(blank=True, choices=[('rub', 'руб.'), ('rub_km', 'руб./км'), ('rub_kg', 'руб./кг'), ('rub_cbm', 'руб./куб'), ('rub_hour', 'руб./час')], default='rub', max_length=20, verbose_name='Единица измерения (перевозчик)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='carrier_payment_condition',
            field=models.CharField(blank=True, choices=[('documents', 'По факту предоставления документов'), ('unloading', 'Оплата на выгрузке')], default='', max_length=50, verbose_name='Условия оплаты (перевозчик)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='carrier_payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Наличными (в т.ч. на карту)'), ('cashless_vat', 'Безнал с НДС'), ('cashless_no_vat', 'Безнал без НДС')], default='', max_length=20, verbose_name='Форма оплаты (перевозчик)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='carrier_payment_term',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Срок оплаты (перевозчик, банк. дней)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='carrier_vat_rate',
            field=models.CharField(blank=True, choices=[('20', '20%'), ('10', '10%'), ('7', '7%'), ('5', '5%'), ('0', '0%')], default='', max_length=5, verbose_name='Ставка НДС (перевозчик)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='client_cost_unit',
            field=models.CharField(blank=True, choices=[('rub', 'руб.'), ('rub_km', 'руб./км'), ('rub_kg', 'руб./кг'), ('rub_cbm', 'руб./куб'), ('rub_hour', 'руб./час')], default='rub', max_length=20, verbose_name='Единица измерения (заказчик)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='client_payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Наличными (в т.ч. на карту)'), ('cashless_vat', 'Безнал с НДС'), ('cashless_no_vat', 'Безнал без НДС')], default='', max_length=20, verbose_name='Форма оплаты (заказчик)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='client_vat_rate',
            field=models.CharField(blank=True, choices=[('20', '20%'), ('10', '10%'), ('7', '7%'), ('5', '5%'), ('0', '0%')], default='', max_length=5, verbose_name='Ставка НДС (заказчик)'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='carrier_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[trips.validators.RussianMinValueValidator(0)], verbose_name='Ставка перевозчику'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='client_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[trips.validators.RussianMinValueValidator(0)], verbose_name='Ставка заказчику'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='payment_condition',
            field=models.CharField(blank=True, choices=[('documents', 'По факту предоставления документов'), ('unloading', 'Оплата на выгрузке')], default='', max_length=50, verbose_name='Условия оплаты (заказчик)'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='payment_term',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Срок оплаты (заказчик, банк. дней)'),
        ),
    ]
