# Generated by Django 5.2.11 on 2026-03-25 13:23

import trips.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0030_remove_trip_payment_type_trip_carrier_cost_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='carrier_financial_status',
            field=models.CharField(choices=[('open', 'Открыт'), ('calculated', 'Зафиксирован'), ('invoiced', 'Документы выставлены'), ('paid', 'Оплачен')], default='open', max_length=20, verbose_name='Статус расчётов (перевозчик)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='carrier_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Фактический пробег (км) или время (ч) для расчёта итоговой суммы', max_digits=10, null=True, verbose_name='Фактически (перевозчик)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='carrier_total_fixed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Итоговая сумма (перевозчик, зафиксирована)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='client_financial_status',
            field=models.CharField(choices=[('open', 'Открыт'), ('calculated', 'Зафиксирован'), ('invoiced', 'Документы выставлены'), ('paid', 'Оплачен')], default='open', max_length=20, verbose_name='Статус расчётов (заказчик)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='client_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Фактический пробег (км) или время (ч) для расчёта итоговой суммы', max_digits=10, null=True, verbose_name='Фактически (заказчик)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='client_total_fixed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Итоговая сумма (заказчик, зафиксирована)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[trips.validators.RussianMinValueValidator(0)], verbose_name='Объём (м³)'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес (кг)'),
        ),
    ]
