# Generated by Django 5.2.11 on 2026-03-30 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0021_migrate_contacts_from_person'),
        ('trips', '0031_trip_carrier_financial_status_trip_carrier_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='consignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips_as_consignee', to='organizations.organization', verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='consignor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips_as_consignor', to='organizations.organization', verbose_name='Отправитель'),
        ),
    ]
