# Generated by Django 5.2.11 on 2026-03-30 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0032_make_consignor_consignee_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date_of_trip',
            field=models.DateField(default=datetime.date(2000, 1, 1), verbose_name='Дата заявки'),
        ),
    ]
