# Generated by Django 5.2.11 on 2026-04-01 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0021_migrate_contacts_from_person'),
        ('trips', '0033_make_date_of_trip_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='trippoint',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Грузоотправитель (для погрузки) или грузополучатель (для выгрузки)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trip_points', to='organizations.organization', verbose_name='Организация'),
        ),
    ]
