# Generated by Django 5.2.11 on 2026-04-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0035_backfill_trippoint_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date_of_trip',
            field=models.DateField(verbose_name='Дата заявки'),
        ),
    ]
