# Generated by Django 5.2.11 on 2026-04-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0036_alter_trip_date_of_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trippoint',
            name='actual_date_new',
            field=models.DateField(blank=True, null=True, verbose_name='Фактическая дата'),
        ),
        migrations.AddField(
            model_name='trippoint',
            name='actual_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Фактическое время'),
        ),
        migrations.AddField(
            model_name='trippoint',
            name='planned_date_new',
            field=models.DateField(blank=True, null=True, verbose_name='Заявленная дата'),
        ),
        migrations.AddField(
            model_name='trippoint',
            name='planned_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Заявленное время'),
        ),
    ]
