# Generated by Django 5.2.11 on 2026-04-01 15:34

from django.db import migrations


def copy_datetime_to_split_fields(apps, schema_editor):
    TripPoint = apps.get_model("trips", "TripPoint")
    for pt in TripPoint.objects.all():
        if pt.planned_date:
            pt.planned_date_new = pt.planned_date.date()
            time_val = pt.planned_date.time()
            if time_val.hour or time_val.minute or time_val.second:
                pt.planned_time = time_val
        if pt.actual_date:
            pt.actual_date_new = pt.actual_date.date()
            time_val = pt.actual_date.time()
            if time_val.hour or time_val.minute or time_val.second:
                pt.actual_time = time_val
        pt.save(update_fields=[
            "planned_date_new", "planned_time",
            "actual_date_new", "actual_time",
        ])


def copy_split_fields_to_datetime(apps, schema_editor):
    """Обратная миграция: собираем date+time обратно в datetime."""
    from datetime import datetime, time as dt_time

    TripPoint = apps.get_model("trips", "TripPoint")
    for pt in TripPoint.objects.all():
        if pt.planned_date_new:
            t = pt.planned_time or dt_time(0, 0)
            pt.planned_date = datetime.combine(pt.planned_date_new, t)
        if pt.actual_date_new:
            t = pt.actual_time or dt_time(0, 0)
            pt.actual_date = datetime.combine(pt.actual_date_new, t)
        pt.save(update_fields=["planned_date", "actual_date"])


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0037_split_datetime_step1_add_new_fields'),
    ]

    operations = [
        migrations.RunPython(
            copy_datetime_to_split_fields,
            copy_split_fields_to_datetime,
        ),
    ]
