# Generated by Django 5.2.11 on 2026-04-02 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0039_split_datetime_step3_swap_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='consignee',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='consignor',
        ),
    ]
