# Generated by Django 5.2.11 on 2026-04-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0040_remove_consignor_consignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trippoint',
            name='planned_date',
            field=models.DateField(verbose_name='Заявленная дата'),
        ),
    ]
