# Generated by Django 5.2.11 on 2026-04-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0044_vat_rate_text_to_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='carrier_vat_rate',
            field=models.IntegerField(blank=True, choices=[(0, '0%'), (5, '5%'), (7, '7%'), (10, '10%'), (22, '22%')], null=True, verbose_name='Ставка НДС (перевозчик)'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='client_vat_rate',
            field=models.IntegerField(blank=True, choices=[(0, '0%'), (5, '5%'), (7, '7%'), (10, '10%'), (22, '22%')], null=True, verbose_name='Ставка НДС (заказчик)'),
        ),
    ]
