# Generated by Django 5.2.11 on 2026-04-14 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0024_alter_organization_unique_inn_per_account_and_more'),
        ('trips', '0046_simplify_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='forwarder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips_as_forwarder', to='organizations.organization', verbose_name='Экспедитор'),
        ),
    ]
