# Generated by Django 5.2.13 on 2026-04-30 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0024_alter_organization_unique_inn_per_account_and_more'),
        ('persons', '0026_make_patronymic_optional'),
        ('trips', '0049_trip_deleted_at'),
        ('vehicles', '0016_add_vehiclefueling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips_as_carrier', to='organizations.organization', verbose_name='Перевозчик'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips_as_driver', to='persons.person', verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips_as_truck', to='vehicles.vehicle', verbose_name='Автомобиль'),
        ),
    ]
